# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'shonre' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Analytics'
  pod 'ApphudSDK'
  pod 'Amplitude', '~> 8.3.0'
  pod 'Introspect'
  pod 'lottie-ios'
  # Pods for shonre

  target 'shonreTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'shonreUITests' do
    # Pods for testing
  end

end
